name: Formatter

on: 
  push:
    #branches: [ 1.12.2 ]
    paths-ignore: '**/*nfo.json'
    

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build formatter
        run: dotnet publish .\src\Formatter\Formatter.csproj -c Release -o ./ -r win-x64 -p:PublishSingleFile=true

      - name: Run formatter
        run: .\Formatter

      - name: Push  to github
        if: ${{github.event}} == 'push'
        run: |
          ri .\Formatter.exe -Force
          $ErrorActionPreference ='Continue'
          git config --global credential.helper manager
          git config --global user.email "fanng233@gmail.com"
          git config --global user.name "CfpaBot"
          @"
          protocol=https
          host=github.com
          username=baka-gourd
          password=${{secrets.BAKA_GOURD_TOKEN}}
          "@ > .\1.txt
          gc 1.txt|git credential-manager  store
          ri .\1.txt -Force
          git add .
          git commit -m "Format file"
          git push origin HEAD:${{ github.ref }}